import type { TarotCard } from "./types";

export const majorArcana: TarotCard[] = [
  {
    id: "the_fool",
    arcana: "major",
    number: 0,
    roman: "0",
    name: "The Fool",
    koreanName: "바보",
    keywords: ["시작", "모험", "가능성"],
    description: "새로운 길 앞에 선 순수한 시작의 상징.",
    visual: { symbol: "✦", palette: "bright" },
  },
  {
    id: "the_magician",
    arcana: "major",
    number: 1,
    roman: "I",
    name: "The Magician",
    koreanName: "마법사",
    keywords: ["실행", "도구", "의지"],
    description: "가능성을 현실로 바꾸는 힘.",
    visual: { symbol: "⚚", palette: "bright" },
  },
  {
    id: "the_high_priestess",
    arcana: "major",
    number: 2,
    roman: "II",
    name: "The High Priestess",
    koreanName: "여사제",
    keywords: ["직감", "비밀", "내면"],
    description: "말로 드러나지 않는 지혜와 감각.",
    visual: { symbol: "☾", palette: "dark" },
  },
  {
    id: "the_empress",
    arcana: "major",
    number: 3,
    roman: "III",
    name: "The Empress",
    koreanName: "여황제",
    keywords: ["풍요", "성장", "돌봄"],
    description: "자라나는 것들을 품는 풍요의 힘.",
    visual: { symbol: "♀", palette: "hope" },
  },
  {
    id: "the_emperor",
    arcana: "major",
    number: 4,
    roman: "IV",
    name: "The Emperor",
    koreanName: "황제",
    keywords: ["질서", "책임", "구조"],
    description: "흔들리는 것을 세우는 구조와 책임.",
    visual: { symbol: "♔", palette: "neutral" },
  },
  {
    id: "the_hierophant",
    arcana: "major",
    number: 5,
    roman: "V",
    name: "The Hierophant",
    koreanName: "교황",
    keywords: ["전통", "가르침", "신뢰"],
    description: "축적된 지혜와 배움의 문.",
    visual: { symbol: "⚿", palette: "neutral" },
  },
  {
    id: "the_lovers",
    arcana: "major",
    number: 6,
    roman: "VI",
    name: "The Lovers",
    koreanName: "연인",
    keywords: ["관계", "선택", "조화"],
    description: "마음과 선택이 만나는 지점.",
    visual: { symbol: "♥", palette: "hope" },
  },
  {
    id: "the_chariot",
    arcana: "major",
    number: 7,
    roman: "VII",
    name: "The Chariot",
    koreanName: "전차",
    keywords: ["전진", "통제", "의지"],
    description: "상반된 힘을 붙잡고 앞으로 나아감.",
    visual: { symbol: "◈", palette: "bright" },
  },
  {
    id: "strength",
    arcana: "major",
    number: 8,
    roman: "VIII",
    name: "Strength",
    koreanName: "힘",
    keywords: ["용기", "인내", "부드러운 힘"],
    description: "강압이 아닌 부드러운 용기의 힘.",
    visual: { symbol: "∞", palette: "bright" },
  },
  {
    id: "the_hermit",
    arcana: "major",
    number: 9,
    roman: "IX",
    name: "The Hermit",
    koreanName: "은둔자",
    keywords: ["탐색", "고요", "내면"],
    description: "혼자만의 등불로 길을 찾는 시간.",
    visual: { symbol: "☼", palette: "dark" },
  },
  {
    id: "wheel_of_fortune",
    arcana: "major",
    number: 10,
    roman: "X",
    name: "Wheel of Fortune",
    koreanName: "운명의 수레바퀴",
    keywords: ["변화", "순환", "전환점"],
    description: "흐름이 바뀌는 운명의 회전.",
    visual: { symbol: "◎", palette: "bright" },
  },
  {
    id: "justice",
    arcana: "major",
    number: 11,
    roman: "XI",
    name: "Justice",
    koreanName: "정의",
    keywords: ["균형", "판단", "책임"],
    description: "선택의 무게와 공정한 판단.",
    visual: { symbol: "⚖", palette: "neutral" },
  },
  {
    id: "the_hanged_man",
    arcana: "major",
    number: 12,
    roman: "XII",
    name: "The Hanged Man",
    koreanName: "매달린 사람",
    keywords: ["멈춤", "관점 전환", "기다림"],
    description: "멈춤 속에서 다른 각도를 발견함.",
    visual: { symbol: "⊕", palette: "dark" },
  },
  {
    id: "death",
    arcana: "major",
    number: 13,
    roman: "XIII",
    name: "Death",
    koreanName: "죽음",
    keywords: ["끝", "전환", "새 시작"],
    description: "무언가가 끝나며 새로운 형태가 열림.",
    visual: { symbol: "✧", palette: "danger" },
  },
  {
    id: "temperance",
    arcana: "major",
    number: 14,
    roman: "XIV",
    name: "Temperance",
    koreanName: "절제",
    keywords: ["조화", "균형", "회복"],
    description: "서로 다른 흐름을 알맞게 섞는 지혜.",
    visual: { symbol: "♒", palette: "hope" },
  },
  {
    id: "the_devil",
    arcana: "major",
    number: 15,
    roman: "XV",
    name: "The Devil",
    koreanName: "악마",
    keywords: ["집착", "속박", "유혹"],
    description: "스스로 묶인 사슬을 알아차리는 카드.",
    visual: { symbol: "♆", palette: "danger" },
  },
  {
    id: "the_tower",
    arcana: "major",
    number: 16,
    roman: "XVI",
    name: "The Tower",
    koreanName: "탑",
    keywords: ["붕괴", "충격", "해방"],
    description: "낡은 구조가 무너지며 진실이 드러남.",
    visual: { symbol: "↯", palette: "danger" },
  },
  {
    id: "the_star",
    arcana: "major",
    number: 17,
    roman: "XVII",
    name: "The Star",
    koreanName: "별",
    keywords: ["희망", "치유", "영감"],
    description: "어둠 뒤에 남은 회복과 희망의 빛.",
    visual: { symbol: "★", palette: "hope" },
  },
  {
    id: "the_moon",
    arcana: "major",
    number: 18,
    roman: "XVIII",
    name: "The Moon",
    koreanName: "달",
    keywords: ["불안", "직감", "숨겨진 길"],
    description: "안개 속 진실과 무의식의 상징.",
    visual: { symbol: "☽", palette: "dark" },
  },
  {
    id: "the_sun",
    arcana: "major",
    number: 19,
    roman: "XIX",
    name: "The Sun",
    koreanName: "태양",
    keywords: ["활력", "기쁨", "명확함"],
    description: "가려진 것이 밝게 드러나는 시간.",
    visual: { symbol: "☀", palette: "bright" },
  },
  {
    id: "judgement",
    arcana: "major",
    number: 20,
    roman: "XX",
    name: "Judgement",
    koreanName: "심판",
    keywords: ["각성", "부름", "재평가"],
    description: "다시 깨어나 선택을 바라보는 순간.",
    visual: { symbol: "♬", palette: "neutral" },
  },
  {
    id: "the_world",
    arcana: "major",
    number: 21,
    roman: "XXI",
    name: "The World",
    koreanName: "세계",
    keywords: ["완성", "통합", "성취"],
    description: "하나의 순환이 완성되고 넓은 문이 열림.",
    visual: { symbol: "◌", palette: "hope" },
  },
];

export function drawMajorArcana(count: number): TarotCard[] {
  const shuffled = Phaser.Utils.Array.Shuffle([...majorArcana]);
  return shuffled.slice(0, count);
}
